#!/data/data/com.termux/files/usr/bin/sh


sleep 1
sxhkd 2>~/sxhkd.log &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config normal_border_color "#44E0E0E0"
bspc config active_border_color "#4f6f73"
bspc config focused_border_color "#3a6ea5"
bspc config urgent_border_color "#4f6f73"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sleep 1
sxhkd &
feh --bg-fill ~/wallpaper3.jpg &
~/.config/polybar/launch.sh &

